''
  font = "JetBrains Mono"
  font-size = 18
  hint-font = true
  text-color = #${mcolours.primary.fg}
  background-color = #${mcolours.primary.bg}
  selection-color = #${mcolours.primary.main}
  input-color = #${mcolours.primary.fg}
  prompt-text = ""
  placeholder-text = ""
  width = 220
  height = 340
  border-width = 0
  border-color = #${mcolours.primary.fg}
  outline-width = 2
  outline-color = #${mcolours.primary.bg}
  corner-radius = 5
  text-background-corner-radius = 5
  padding-top = 8
  padding-bottom = 8
  padding-left = 8
  padding-right = 8
  anchor = center
  drun-launch = true
  history = true
  fuzzy-match = true
  terminal = alacritty
  ascii-input = false
''
